using Microsoft.Data;
using Microsoft.Data.SqlClient;
using Microsoft.Data.SqlTypes;
using OnnxTextEmbeddings;
using OnnxTextEmbeddings.SqlServer;

namespace SemanticKnowledge.SqlServer;

internal sealed class SqlServerKnowledgeStorageProvider(
    SemanticKnowledgeSqlServerOptions options,
    SqlServerSemanticSearch semanticSearch) : IKnowledgeStorageProvider
{
    private const int EngineVersion = 1;
    private readonly SemaphoreSlim _gate = new(1, 1);
    private string? _activeVectorTable;
    private string? _writeVectorTable;
    private string? _pendingVectorTable;

    public async Task<KnowledgeProviderCapabilities> InitializeAsync(KnowledgeStorageInitialization initialization, CancellationToken cancellationToken = default)
    {
        if (initialization.Embedding.OutputDimensions > SqlServerVectorLimits.MaximumDimensions)
            throw new InvalidOperationException($"The configured embedding space is {initialization.Embedding.OutputDimensions}-dimensional, but SQL Server VECTOR supports at most {SqlServerVectorLimits.MaximumDimensions}. Configure Embeddings.OutputDimensions explicitly; SemanticKnowledge never silently performs lossy reduction.");
        await _gate.WaitAsync(cancellationToken).ConfigureAwait(false);
        try
        {
            await using var connection = await OpenAsync(cancellationToken).ConfigureAwait(false);
            var vectorCapabilities = await SqlServerSemanticSearch.GetCapabilitiesAsync(connection, cancellationToken).ConfigureAwait(false);
            if (!vectorCapabilities.SupportsVectorType) throw new InvalidOperationException("This SQL Server/Azure SQL database does not expose the required native VECTOR/VECTOR_DISTANCE surface.");
            await CreateBaseSchemaAsync(connection, cancellationToken).ConfigureAwait(false);
            var metadata = await ReadMetadataAsync(connection, cancellationToken).ConfigureAwait(false); var rebuild = false;
            if (metadata is null)
            {
                var generation = Guid.NewGuid(); var table = VectorTableName(generation); await CreateVectorTableAsync(connection, table, initialization.Embedding.OutputDimensions, cancellationToken).ConfigureAwait(false); await InsertMetadataAsync(connection, initialization, generation, table, cancellationToken).ConfigureAwait(false); _activeVectorTable = _writeVectorTable = table;
            }
            else
            {
                if (metadata.DatabaseVersion != initialization.DatabaseVersion) throw new InvalidOperationException($"Stored SemanticKnowledge database version is {metadata.DatabaseVersion}, configured version is {initialization.DatabaseVersion}. Register/apply a logical migration before opening this store.");
                _activeVectorTable = metadata.ActiveVectorTable;
                var matches = metadata.ActiveDimensions == initialization.Embedding.OutputDimensions && string.Equals(metadata.ActiveFingerprint, initialization.Embedding.EmbeddingSpaceFingerprint, StringComparison.Ordinal);
                if (matches)
                {
                    _writeVectorTable = _activeVectorTable; if (!string.IsNullOrWhiteSpace(metadata.PendingVectorTable)) await DropVectorTableIfExistsAsync(connection, metadata.PendingVectorTable!, cancellationToken).ConfigureAwait(false); await ClearPendingMetadataAsync(connection, cancellationToken).ConfigureAwait(false);
                }
                else
                {
                    if (!string.IsNullOrWhiteSpace(metadata.PendingVectorTable)) await DropVectorTableIfExistsAsync(connection, metadata.PendingVectorTable!, cancellationToken).ConfigureAwait(false);
                    var generation = Guid.NewGuid(); var table = VectorTableName(generation); await CreateVectorTableAsync(connection, table, initialization.Embedding.OutputDimensions, cancellationToken).ConfigureAwait(false); await SetPendingMetadataAsync(connection, initialization, generation, table, cancellationToken).ConfigureAwait(false); _pendingVectorTable = table; _writeVectorTable = table; rebuild = true;
                }
            }
            return new KnowledgeProviderCapabilities { Provider = "SQL Server 2025/Azure SQL", MaxDimensions = SqlServerVectorLimits.MaximumDimensions, PhysicalVectorStorage = "VECTOR(float32)", ExactVectorSearch = true, ApproximateVectorSearch = vectorCapabilities.SupportsApproximateSearch, NativeAotSupported = false, RequiresEmbeddingRebuild = rebuild };
        }
        finally { _gate.Release(); }
    }

    public async Task CompleteEmbeddingRebuildAsync(CancellationToken cancellationToken = default)
    {
        if (_pendingVectorTable is null) return; await _gate.WaitAsync(cancellationToken).ConfigureAwait(false);
        try
        {
            await using var connection = await OpenAsync(cancellationToken).ConfigureAwait(false); await using var transaction = (SqlTransaction)await connection.BeginTransactionAsync(cancellationToken).ConfigureAwait(false); var old = _activeVectorTable;
            await using (var command = new SqlCommand($"UPDATE {Q("sk_store_metadata")} SET active_generation=pending_generation,active_vector_table=pending_vector_table,active_fingerprint=pending_fingerprint,active_dimensions=pending_dimensions,pending_generation=NULL,pending_vector_table=NULL,pending_fingerprint=NULL,pending_dimensions=NULL WHERE singleton=1", connection, transaction)) await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
            await transaction.CommitAsync(cancellationToken).ConfigureAwait(false); _activeVectorTable = _pendingVectorTable; _pendingVectorTable = null; _writeVectorTable = _activeVectorTable; if (!string.IsNullOrWhiteSpace(old) && !string.Equals(old, _activeVectorTable, StringComparison.Ordinal)) await DropVectorTableIfExistsAsync(connection, old!, cancellationToken).ConfigureAwait(false);
        }
        finally { _gate.Release(); }
    }

    public async Task<KnowledgeBaseRecord> GetOrCreateKnowledgeBaseAsync(string title, string? externalId = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(title); await using var connection = await OpenAsync(cancellationToken).ConfigureAwait(false); var found = await FindKnowledgeBaseAsync(connection, title, externalId, cancellationToken).ConfigureAwait(false); if (found is not null) return found;
        var record = new KnowledgeBaseRecord { Id = Guid.NewGuid(), ExternalId = externalId, Title = title.Trim() }; await using var command = new SqlCommand($"INSERT INTO {Q("sk_knowledge_bases")}(id,external_id,title,description) VALUES(@id,@external,@title,N'')", connection); command.Parameters.AddWithValue("@id", record.Id); command.Parameters.AddWithValue("@external", (object?)externalId ?? DBNull.Value); command.Parameters.AddWithValue("@title", record.Title); await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false); return record;
    }

    public async Task<KnowledgeCollectionRecord> GetOrCreateCollectionAsync(Guid knowledgeBaseId, string title, Guid? parentCollectionId = null, Guid? defaultSchemaId = null, string? externalId = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(title); await using var connection = await OpenAsync(cancellationToken).ConfigureAwait(false); var found = await FindCollectionAsync(connection, knowledgeBaseId, title, parentCollectionId, externalId, cancellationToken).ConfigureAwait(false); if (found is not null) return found;
        var record = new KnowledgeCollectionRecord { Id = Guid.NewGuid(), KnowledgeBaseId = knowledgeBaseId, ParentCollectionId = parentCollectionId, DefaultSchemaId = defaultSchemaId, ExternalId = externalId, Title = title.Trim() }; await using var command = new SqlCommand($"INSERT INTO {Q("sk_collections")}(id,knowledge_base_id,parent_collection_id,default_schema_id,external_id,title,description) VALUES(@id,@kb,@parent,@schema,@external,@title,N'')", connection); command.Parameters.AddWithValue("@id", record.Id); command.Parameters.AddWithValue("@kb", knowledgeBaseId); command.Parameters.AddWithValue("@parent", (object?)parentCollectionId ?? DBNull.Value); command.Parameters.AddWithValue("@schema", (object?)defaultSchemaId ?? DBNull.Value); command.Parameters.AddWithValue("@external", (object?)externalId ?? DBNull.Value); command.Parameters.AddWithValue("@title", record.Title); await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false); return record;
    }

    public async Task<IReadOnlyList<KnowledgeCollectionRecord>> GetCollectionsAsync(Guid? knowledgeBaseId = null, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenAsync(cancellationToken).ConfigureAwait(false); var rows = new List<KnowledgeCollectionRecord>(); await using (var command = new SqlCommand($"SELECT id,knowledge_base_id,parent_collection_id,default_schema_id,external_id,title,description FROM {Q("sk_collections")}" + (knowledgeBaseId is null ? "" : " WHERE knowledge_base_id=@kb") + " ORDER BY title", connection)) { if (knowledgeBaseId is { } kb) command.Parameters.AddWithValue("@kb", kb); await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false); while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false)) rows.Add(new KnowledgeCollectionRecord { Id = reader.GetGuid(0), KnowledgeBaseId = reader.GetGuid(1), ParentCollectionId = reader.IsDBNull(2) ? null : reader.GetGuid(2), DefaultSchemaId = reader.IsDBNull(3) ? null : reader.GetGuid(3), ExternalId = reader.IsDBNull(4) ? null : reader.GetString(4), Title = reader.GetString(5), Description = reader.GetString(6) }); }
        var result = new List<KnowledgeCollectionRecord>(rows.Count); foreach (var row in rows) result.Add(row with { Tags = await ReadCollectionTagsAsync(connection, row.Id, cancellationToken).ConfigureAwait(false) }); return result;
    }

    public async Task UpsertCollectionSemanticSourcesAsync(KnowledgeCollectionRecord collection, IReadOnlyList<SemanticSourceRecord> semanticSources, CancellationToken cancellationToken = default) { await using var connection = await OpenAsync(cancellationToken).ConfigureAwait(false); await using var transaction = (SqlTransaction)await connection.BeginTransactionAsync(cancellationToken).ConfigureAwait(false); await DeleteSemanticRowsAsync(connection, transaction, collection.Id, SemanticEntityKind.Collection, cancellationToken).ConfigureAwait(false); foreach (var source in semanticSources) await InsertSemanticSourceAsync(connection, transaction, source, cancellationToken).ConfigureAwait(false); await transaction.CommitAsync(cancellationToken).ConfigureAwait(false); }

    public async Task UpsertSchemaAsync(KnowledgeSchemaDefinition schema, CancellationToken cancellationToken = default)
    {
        schema.Validate(); await using var connection = await OpenAsync(cancellationToken).ConfigureAwait(false); await using var transaction = (SqlTransaction)await connection.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);
        await using (var command = new SqlCommand($"UPDATE {Q("sk_schemas")} SET schema_key=@key,display_name=@name,revision=@revision WHERE id=@id; IF @@ROWCOUNT=0 INSERT INTO {Q("sk_schemas")}(id,schema_key,display_name,revision) VALUES(@id,@key,@name,@revision);", connection, transaction)) { command.Parameters.AddWithValue("@id", schema.Id); command.Parameters.AddWithValue("@key", schema.Key); command.Parameters.AddWithValue("@name", schema.DisplayName); command.Parameters.AddWithValue("@revision", schema.Revision); await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false); }
        await ExecuteAsync(connection, transaction, $"DELETE FROM {Q("sk_schema_fields")} WHERE schema_id=@id", cancellationToken, ("@id", schema.Id)).ConfigureAwait(false);
        for (var ordinal = 0; ordinal < schema.Fields.Count; ordinal++) { var field = schema.Fields[ordinal]; await using var command = new SqlCommand($"INSERT INTO {Q("sk_schema_fields")}(id,schema_id,field_key,display_name,field_type,required_flag,system_flag,filterable,semantic_mode,semantic_weight,ordinal) VALUES(@id,@schema,@key,@name,@type,@required,@system,@filterable,@mode,@weight,@ordinal)", connection, transaction); command.Parameters.AddWithValue("@id", field.Id); command.Parameters.AddWithValue("@schema", schema.Id); command.Parameters.AddWithValue("@key", field.Key); command.Parameters.AddWithValue("@name", field.DisplayName); command.Parameters.AddWithValue("@type", (int)field.Type); command.Parameters.AddWithValue("@required", field.Required); command.Parameters.AddWithValue("@system", field.System); command.Parameters.AddWithValue("@filterable", field.Filterable); command.Parameters.AddWithValue("@mode", (int)field.SemanticMode); command.Parameters.AddWithValue("@weight", field.SemanticWeightPercent); command.Parameters.AddWithValue("@ordinal", ordinal); await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false); }
        await transaction.CommitAsync(cancellationToken).ConfigureAwait(false);
    }

    public async Task<KnowledgeSchemaDefinition?> GetSchemaAsync(Guid schemaId, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenAsync(cancellationToken).ConfigureAwait(false); string key, display; int revision; await using (var command = new SqlCommand($"SELECT schema_key,display_name,revision FROM {Q("sk_schemas")} WHERE id=@id", connection)) { command.Parameters.AddWithValue("@id", schemaId); await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false); if (!await reader.ReadAsync(cancellationToken).ConfigureAwait(false)) return null; key = reader.GetString(0); display = reader.GetString(1); revision = reader.GetInt32(2); }
        var fields = new List<KnowledgeSchemaField>(); await using (var command = new SqlCommand($"SELECT id,field_key,display_name,field_type,required_flag,system_flag,filterable,semantic_mode,semantic_weight FROM {Q("sk_schema_fields")} WHERE schema_id=@id ORDER BY ordinal", connection)) { command.Parameters.AddWithValue("@id", schemaId); await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false); while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false)) fields.Add(new KnowledgeSchemaField { Id = reader.GetGuid(0), Key = reader.GetString(1), DisplayName = reader.GetString(2), Type = (KnowledgeFieldType)reader.GetInt32(3), Required = reader.GetBoolean(4), System = reader.GetBoolean(5), Filterable = reader.GetBoolean(6), SemanticMode = (SemanticMode)reader.GetInt32(7), SemanticWeightPercent = reader.GetInt32(8) }); }
        return new KnowledgeSchemaDefinition { Id = schemaId, Key = key, DisplayName = display, Revision = revision, Fields = fields };
    }

    public async Task UpsertDocumentAsync(KnowledgeDocumentRecord document, IReadOnlyList<SemanticSourceRecord> semanticSources, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenAsync(cancellationToken).ConfigureAwait(false); await using var transaction = (SqlTransaction)await connection.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);
        await using (var command = new SqlCommand($"UPDATE {Q("sk_documents")} SET external_id=@external,knowledge_base_id=@kb,collection_id=@collection,schema_id=@schema,title=@title,description=@description,source_hash=@hash WHERE id=@id; IF @@ROWCOUNT=0 INSERT INTO {Q("sk_documents")}(id,external_id,knowledge_base_id,collection_id,schema_id,title,description,source_hash) VALUES(@id,@external,@kb,@collection,@schema,@title,@description,@hash);", connection, transaction)) { command.Parameters.AddWithValue("@id", document.Id); command.Parameters.AddWithValue("@external", (object?)document.ExternalId ?? DBNull.Value); command.Parameters.AddWithValue("@kb", document.KnowledgeBaseId); command.Parameters.AddWithValue("@collection", document.CollectionId); command.Parameters.AddWithValue("@schema", document.SchemaId); command.Parameters.AddWithValue("@title", document.Title); command.Parameters.AddWithValue("@description", document.Description); command.Parameters.AddWithValue("@hash", (object?)document.SourceHash ?? DBNull.Value); await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false); }
        await ExecuteAsync(connection, transaction, $"DELETE FROM {Q("sk_document_tags")} WHERE document_id=@id", cancellationToken, ("@id", document.Id)).ConfigureAwait(false); await ExecuteAsync(connection, transaction, $"DELETE FROM {Q("sk_document_values")} WHERE document_id=@id", cancellationToken, ("@id", document.Id)).ConfigureAwait(false); foreach (var tag in document.Tags) await ExecuteAsync(connection, transaction, $"INSERT INTO {Q("sk_document_tags")}(document_id,tag) VALUES(@id,@tag)", cancellationToken, ("@id", document.Id), ("@tag", tag)).ConfigureAwait(false); foreach (var pair in document.Values) await InsertValueAsync(connection, transaction, document.Id, pair.Key, pair.Value, cancellationToken).ConfigureAwait(false); await DeleteSemanticRowsAsync(connection, transaction, document.Id, SemanticEntityKind.Document, cancellationToken).ConfigureAwait(false); foreach (var source in semanticSources) await InsertSemanticSourceAsync(connection, transaction, source, cancellationToken).ConfigureAwait(false); await transaction.CommitAsync(cancellationToken).ConfigureAwait(false);
    }

    public async Task<KnowledgeDocumentRecord?> GetDocumentAsync(Guid documentId, CancellationToken cancellationToken = default) { await using var connection = await OpenAsync(cancellationToken).ConfigureAwait(false); return await ReadDocumentAsync(connection, documentId, cancellationToken).ConfigureAwait(false); }
    public async Task<IReadOnlyList<KnowledgeDocumentRecord>> GetDocumentsAsync(Guid? knowledgeBaseId = null, CancellationToken cancellationToken = default) { await using var connection = await OpenAsync(cancellationToken).ConfigureAwait(false); var ids = new List<Guid>(); await using (var command = new SqlCommand($"SELECT id FROM {Q("sk_documents")}" + (knowledgeBaseId is null ? "" : " WHERE knowledge_base_id=@kb"), connection)) { if (knowledgeBaseId is { } kb) command.Parameters.AddWithValue("@kb", kb); await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false); while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false)) ids.Add(reader.GetGuid(0)); } var result = new List<KnowledgeDocumentRecord>(); foreach (var id in ids) if (await ReadDocumentAsync(connection, id, cancellationToken).ConfigureAwait(false) is { } document) result.Add(document); return result; }

    public async Task<IReadOnlyList<KnowledgeSearchHit>> SearchAsync(QueryEmbedding query, KnowledgeSearchRequest request, CancellationToken cancellationToken = default)
    {
        var table = _activeVectorTable ?? throw new InvalidOperationException("SQL Server provider is not initialized."); await using var connection = await OpenAsync(cancellationToken).ConfigureAwait(false); var collectionIds = request.CollectionIds.ToArray();
        if (request.Mode == KnowledgeSearchMode.Smart) { var route = await semanticSearch.SearchAsync<Guid>(connection, query, CandidateQuery(table, "t.item_kind='collection' AND t.knowledge_base_id=@sk_kb"), new DatabaseSemanticSearchOptions { Top = 8, CandidateCount = 100 }, command => command.Parameters.AddWithValue("@sk_kb", request.KnowledgeBaseId), cancellationToken: cancellationToken).ConfigureAwait(false); collectionIds = route.Results.Select(x => x.Item).Distinct().ToArray(); }
        if (collectionIds.Length > 0 && request.IncludeDescendants) collectionIds = await ExpandCollectionsAsync(connection, collectionIds, cancellationToken).ConfigureAwait(false);
        var compiled = SqlServerFilterCompiler.Compile(request.Filter, options.Schema); var scope = BuildScopeSql(collectionIds, out var scopeParameters); var where = $"t.item_kind='document' AND t.knowledge_base_id=@sk_kb AND t.item_id IN (SELECT d.id FROM {Q("sk_documents")} d WHERE d.knowledge_base_id=@sk_kb AND ({compiled.Sql}){scope})";
        var search = await semanticSearch.SearchAsync<Guid>(connection, query, CandidateQuery(table, where), new DatabaseSemanticSearchOptions { Top = request.Top, CandidateCount = request.CandidateCount }, command => { command.Parameters.AddWithValue("@sk_kb", request.KnowledgeBaseId); foreach (var p in compiled.Parameters) command.Parameters.Add(Clone(p)); foreach (var p in scopeParameters) command.Parameters.Add(Clone(p)); }, cancellationToken: cancellationToken).ConfigureAwait(false);
        var hits = new List<KnowledgeSearchHit>(); foreach (var result in search.Results) { var document = await ReadDocumentAsync(connection, result.Item, cancellationToken).ConfigureAwait(false); if (document is null) continue; var matches = result.Fields.SelectMany(field => field.Matches.Select(match => new KnowledgeMatchedChunk { FieldKey = field.Name, RawSimilarity = match.RawSimilarity, AdjustedSimilarity = match.AdjustedSimilarity, TokenCount = match.Embedding.Source.TokenCount, CharacterRange = match.Embedding.Source.CharacterRange, Text = request.Include == KnowledgeResultInclude.MetadataOnly ? null : match.Embedding.Text })).ToArray(); hits.Add(new KnowledgeSearchHit { DocumentId = document.Id, CollectionId = document.CollectionId, SchemaId = document.SchemaId, Score = result.Score, Title = document.Title, Description = document.Description, Tags = document.Tags, Matches = matches, Scoring = result.Scoring }); } return hits;
    }

    public async Task DeleteDocumentAsync(Guid documentId, CancellationToken cancellationToken = default) { await using var connection = await OpenAsync(cancellationToken).ConfigureAwait(false); await using var transaction = (SqlTransaction)await connection.BeginTransactionAsync(cancellationToken).ConfigureAwait(false); await DeleteSemanticRowsAsync(connection, transaction, documentId, SemanticEntityKind.Document, cancellationToken).ConfigureAwait(false); await ExecuteAsync(connection, transaction, $"DELETE FROM {Q("sk_document_tags")} WHERE document_id=@id; DELETE FROM {Q("sk_document_values")} WHERE document_id=@id; DELETE FROM {Q("sk_documents")} WHERE id=@id", cancellationToken, ("@id", documentId)).ConfigureAwait(false); await transaction.CommitAsync(cancellationToken).ConfigureAwait(false); }

    public async Task ResetAsync(CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenAsync(cancellationToken).ConfigureAwait(false); var metadata = await ReadMetadataAsync(connection, cancellationToken).ConfigureAwait(false); if (metadata is not null) { await DropVectorTableIfExistsAsync(connection, metadata.ActiveVectorTable, cancellationToken).ConfigureAwait(false); if (!string.IsNullOrWhiteSpace(metadata.PendingVectorTable)) await DropVectorTableIfExistsAsync(connection, metadata.PendingVectorTable!, cancellationToken).ConfigureAwait(false); }
        var tables = new[] { "sk_semantic_sources", "sk_document_values", "sk_document_tags", "sk_documents", "sk_schema_fields", "sk_schemas", "sk_collection_tags", "sk_collections", "sk_knowledge_bases", "sk_store_metadata" }; foreach (var table in tables) { await using var command = new SqlCommand($"IF OBJECT_ID(N'{Q(table)}',N'U') IS NOT NULL DROP TABLE {Q(table)}", connection); await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false); } await using (var schema = new SqlCommand($"IF SCHEMA_ID(N'{options.Schema.Replace("'", "''", StringComparison.Ordinal)}') IS NOT NULL EXEC(N'DROP SCHEMA {QI(options.Schema)}')", connection)) await schema.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false); _activeVectorTable = _writeVectorTable = _pendingVectorTable = null;
    }

    private async Task<SqlConnection> OpenAsync(CancellationToken cancellationToken) { var connection = new SqlConnection(options.ConnectionString); await connection.OpenAsync(cancellationToken).ConfigureAwait(false); return connection; }

    private async Task CreateBaseSchemaAsync(SqlConnection connection, CancellationToken cancellationToken)
    {
        var schemaLiteral = options.Schema.Replace("'", "''", StringComparison.Ordinal); await using var command = new SqlCommand($"""
            IF SCHEMA_ID(N'{schemaLiteral}') IS NULL EXEC(N'CREATE SCHEMA {QI(options.Schema)}');
            IF OBJECT_ID(N'{Q("sk_store_metadata")}',N'U') IS NULL CREATE TABLE {Q("sk_store_metadata")}(singleton smallint NOT NULL PRIMARY KEY CHECK(singleton=1),store_id uniqueidentifier NOT NULL,engine_version int NOT NULL,database_version int NOT NULL,persistence_mode int NOT NULL,active_generation uniqueidentifier NOT NULL,active_vector_table nvarchar(128) NOT NULL,active_fingerprint nvarchar(512) NOT NULL,active_dimensions int NOT NULL,pending_generation uniqueidentifier NULL,pending_vector_table nvarchar(128) NULL,pending_fingerprint nvarchar(512) NULL,pending_dimensions int NULL);
            IF OBJECT_ID(N'{Q("sk_knowledge_bases")}',N'U') IS NULL CREATE TABLE {Q("sk_knowledge_bases")}(id uniqueidentifier NOT NULL PRIMARY KEY,external_id nvarchar(1024) NULL,title nvarchar(2048) NOT NULL,description nvarchar(max) NOT NULL DEFAULT N'');
            IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'ux_sk_mssql_kb_external' AND object_id=OBJECT_ID(N'{Q("sk_knowledge_bases")}')) CREATE UNIQUE INDEX ux_sk_mssql_kb_external ON {Q("sk_knowledge_bases")}(external_id) WHERE external_id IS NOT NULL;
            IF OBJECT_ID(N'{Q("sk_collections")}',N'U') IS NULL CREATE TABLE {Q("sk_collections")}(id uniqueidentifier NOT NULL PRIMARY KEY,knowledge_base_id uniqueidentifier NOT NULL,parent_collection_id uniqueidentifier NULL,default_schema_id uniqueidentifier NULL,external_id nvarchar(1024) NULL,title nvarchar(2048) NOT NULL,description nvarchar(max) NOT NULL DEFAULT N'');
            IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'ix_sk_mssql_collections_parent' AND object_id=OBJECT_ID(N'{Q("sk_collections")}')) CREATE INDEX ix_sk_mssql_collections_parent ON {Q("sk_collections")}(parent_collection_id);
            IF OBJECT_ID(N'{Q("sk_collection_tags")}',N'U') IS NULL CREATE TABLE {Q("sk_collection_tags")}(collection_id uniqueidentifier NOT NULL,tag nvarchar(512) NOT NULL,CONSTRAINT pk_sk_mssql_collection_tags PRIMARY KEY(collection_id,tag));
            IF OBJECT_ID(N'{Q("sk_schemas")}',N'U') IS NULL CREATE TABLE {Q("sk_schemas")}(id uniqueidentifier NOT NULL PRIMARY KEY,schema_key nvarchar(512) NOT NULL UNIQUE,display_name nvarchar(1024) NOT NULL,revision int NOT NULL);
            IF OBJECT_ID(N'{Q("sk_schema_fields")}',N'U') IS NULL CREATE TABLE {Q("sk_schema_fields")}(id uniqueidentifier NOT NULL PRIMARY KEY,schema_id uniqueidentifier NOT NULL,field_key nvarchar(512) NOT NULL,display_name nvarchar(1024) NOT NULL,field_type int NOT NULL,required_flag bit NOT NULL,system_flag bit NOT NULL,filterable bit NOT NULL,semantic_mode int NOT NULL,semantic_weight int NOT NULL,ordinal int NOT NULL,CONSTRAINT ux_sk_mssql_schema_field UNIQUE(schema_id,field_key));
            IF OBJECT_ID(N'{Q("sk_documents")}',N'U') IS NULL CREATE TABLE {Q("sk_documents")}(id uniqueidentifier NOT NULL PRIMARY KEY,external_id nvarchar(1024) NULL,knowledge_base_id uniqueidentifier NOT NULL,collection_id uniqueidentifier NOT NULL,schema_id uniqueidentifier NOT NULL,title nvarchar(2048) NOT NULL,description nvarchar(max) NOT NULL DEFAULT N'',source_hash varchar(64) NULL);
            IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'ix_sk_mssql_documents_collection' AND object_id=OBJECT_ID(N'{Q("sk_documents")}')) CREATE INDEX ix_sk_mssql_documents_collection ON {Q("sk_documents")}(collection_id);
            IF OBJECT_ID(N'{Q("sk_document_tags")}',N'U') IS NULL CREATE TABLE {Q("sk_document_tags")}(document_id uniqueidentifier NOT NULL,tag nvarchar(512) NOT NULL,CONSTRAINT pk_sk_mssql_document_tags PRIMARY KEY(document_id,tag));
            IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'ix_sk_mssql_tags_tag' AND object_id=OBJECT_ID(N'{Q("sk_document_tags")}')) CREATE INDEX ix_sk_mssql_tags_tag ON {Q("sk_document_tags")}(tag);
            IF OBJECT_ID(N'{Q("sk_document_values")}',N'U') IS NULL CREATE TABLE {Q("sk_document_values")}(document_id uniqueidentifier NOT NULL,field_key nvarchar(512) NOT NULL,value_type int NOT NULL,text_value nvarchar(4000) NULL,int_value bigint NULL,decimal_value decimal(38,12) NULL,bool_value bit NULL,datetime_value datetimeoffset NULL,guid_value uniqueidentifier NULL,CONSTRAINT pk_sk_mssql_values PRIMARY KEY(document_id,field_key));
            IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'ix_sk_mssql_values_int' AND object_id=OBJECT_ID(N'{Q("sk_document_values")}')) CREATE INDEX ix_sk_mssql_values_int ON {Q("sk_document_values")}(field_key,int_value); IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'ix_sk_mssql_values_decimal' AND object_id=OBJECT_ID(N'{Q("sk_document_values")}')) CREATE INDEX ix_sk_mssql_values_decimal ON {Q("sk_document_values")}(field_key,decimal_value); IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'ix_sk_mssql_values_datetime' AND object_id=OBJECT_ID(N'{Q("sk_document_values")}')) CREATE INDEX ix_sk_mssql_values_datetime ON {Q("sk_document_values")}(field_key,datetime_value); IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'ix_sk_mssql_values_guid' AND object_id=OBJECT_ID(N'{Q("sk_document_values")}')) CREATE INDEX ix_sk_mssql_values_guid ON {Q("sk_document_values")}(field_key,guid_value);
            IF OBJECT_ID(N'{Q("sk_semantic_sources")}',N'U') IS NULL CREATE TABLE {Q("sk_semantic_sources")}(id uniqueidentifier NOT NULL PRIMARY KEY,item_id uniqueidentifier NOT NULL,entity_kind int NOT NULL,knowledge_base_id uniqueidentifier NOT NULL,collection_id uniqueidentifier NOT NULL,document_id uniqueidentifier NULL,field_id uniqueidentifier NOT NULL,field_key nvarchar(512) NOT NULL,field_weight real NOT NULL,fingerprint nvarchar(512) NOT NULL,token_count int NOT NULL,char_start int NOT NULL,char_length int NOT NULL,record_json nvarchar(max) NOT NULL);
            """, connection); await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
    }

    private async Task CreateVectorTableAsync(SqlConnection connection, string table, int dimensions, CancellationToken cancellationToken) { await using var command = new SqlCommand($"CREATE TABLE {Q(table)}(item_id uniqueidentifier NOT NULL,item_kind varchar(16) NOT NULL,field_name nvarchar(512) NOT NULL,fingerprint nvarchar(512) NOT NULL,knowledge_base_id uniqueidentifier NOT NULL,collection_id uniqueidentifier NOT NULL,embedding VECTOR({dimensions}) NOT NULL,record_json nvarchar(max) NOT NULL,field_weight real NOT NULL)", connection); await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false); }

    private async Task InsertSemanticSourceAsync(SqlConnection connection, SqlTransaction transaction, SemanticSourceRecord source, CancellationToken cancellationToken)
    {
        var table = _writeVectorTable ?? throw new InvalidOperationException("No writable vector generation is configured."); var json = EmbeddingSerializer.SerializeJson(source.Embedding);
        await using (var command = new SqlCommand($"INSERT INTO {Q("sk_semantic_sources")}(id,item_id,entity_kind,knowledge_base_id,collection_id,document_id,field_id,field_key,field_weight,fingerprint,token_count,char_start,char_length,record_json) VALUES(@id,@item,@kind,@kb,@collection,@document,@field,@key,@weight,@fingerprint,@tokens,@start,@length,@json)", connection, transaction)) { command.Parameters.AddWithValue("@id", source.Id); command.Parameters.AddWithValue("@item", source.ItemId); command.Parameters.AddWithValue("@kind", (int)source.EntityKind); command.Parameters.AddWithValue("@kb", source.KnowledgeBaseId); command.Parameters.AddWithValue("@collection", source.CollectionId); command.Parameters.AddWithValue("@document", (object?)source.DocumentId ?? DBNull.Value); command.Parameters.AddWithValue("@field", source.FieldId); command.Parameters.AddWithValue("@key", source.FieldKey); command.Parameters.AddWithValue("@weight", source.ScorerWeight); command.Parameters.AddWithValue("@fingerprint", source.Embedding.Identity.EmbeddingSpaceFingerprint); command.Parameters.AddWithValue("@tokens", source.Embedding.Source.TokenCount); command.Parameters.AddWithValue("@start", source.Embedding.Source.CharacterRange.Start); command.Parameters.AddWithValue("@length", source.Embedding.Source.CharacterRange.Length); command.Parameters.AddWithValue("@json", json); await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false); }
        await using (var command = new SqlCommand($"INSERT INTO {Q(table)}(item_id,item_kind,field_name,fingerprint,knowledge_base_id,collection_id,embedding,record_json,field_weight) VALUES(@item,@kind,@field,@fingerprint,@kb,@collection,@embedding,@json,@weight)", connection, transaction)) { command.Parameters.AddWithValue("@item", source.ItemId); command.Parameters.AddWithValue("@kind", source.EntityKind == SemanticEntityKind.Document ? "document" : "collection"); command.Parameters.AddWithValue("@field", source.FieldKey); command.Parameters.AddWithValue("@fingerprint", source.Embedding.Identity.EmbeddingSpaceFingerprint); command.Parameters.AddWithValue("@kb", source.KnowledgeBaseId); command.Parameters.AddWithValue("@collection", source.CollectionId); command.Parameters.Add(new SqlParameter("@embedding", SqlDbTypeExtensions.Vector) { Value = new SqlVector<float>(source.Embedding.Vector.ToFloat32()) }); command.Parameters.AddWithValue("@json", json); command.Parameters.AddWithValue("@weight", source.ScorerWeight); await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false); }
    }

    private async Task DeleteSemanticRowsAsync(SqlConnection connection, SqlTransaction transaction, Guid itemId, SemanticEntityKind kind, CancellationToken cancellationToken) { await ExecuteAsync(connection, transaction, $"DELETE FROM {Q("sk_semantic_sources")} WHERE item_id=@id AND entity_kind=@kind", cancellationToken, ("@id", itemId), ("@kind", (int)kind)).ConfigureAwait(false); if (_writeVectorTable is { } table) await ExecuteAsync(connection, transaction, $"DELETE FROM {Q(table)} WHERE item_id=@id AND item_kind=@kind", cancellationToken, ("@id", itemId), ("@kind", kind == SemanticEntityKind.Document ? "document" : "collection")).ConfigureAwait(false); }
    private async Task InsertValueAsync(SqlConnection connection, SqlTransaction transaction, Guid documentId, string key, KnowledgeValue value, CancellationToken cancellationToken) { await using var command = new SqlCommand($"INSERT INTO {Q("sk_document_values")}(document_id,field_key,value_type,text_value,int_value,decimal_value,bool_value,datetime_value,guid_value) VALUES(@doc,@key,@type,@text,@int,@decimal,@bool,@datetime,@guid)", connection, transaction); command.Parameters.AddWithValue("@doc", documentId); command.Parameters.AddWithValue("@key", key); command.Parameters.AddWithValue("@type", (int)value.Type); command.Parameters.AddWithValue("@text", (object?)value.Text ?? DBNull.Value); command.Parameters.AddWithValue("@int", (object?)value.Int64 ?? DBNull.Value); command.Parameters.AddWithValue("@decimal", (object?)value.Decimal ?? DBNull.Value); command.Parameters.AddWithValue("@bool", (object?)value.Boolean ?? DBNull.Value); command.Parameters.AddWithValue("@datetime", (object?)value.DateTimeOffset ?? DBNull.Value); command.Parameters.AddWithValue("@guid", (object?)value.Guid ?? DBNull.Value); await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false); }

    private async Task<KnowledgeDocumentRecord?> ReadDocumentAsync(SqlConnection connection, Guid id, CancellationToken cancellationToken)
    {
        string? external, hash; Guid kb, collection, schema; string title, description; await using (var command = new SqlCommand($"SELECT external_id,knowledge_base_id,collection_id,schema_id,title,description,source_hash FROM {Q("sk_documents")} WHERE id=@id", connection)) { command.Parameters.AddWithValue("@id", id); await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false); if (!await reader.ReadAsync(cancellationToken).ConfigureAwait(false)) return null; external = reader.IsDBNull(0) ? null : reader.GetString(0); kb = reader.GetGuid(1); collection = reader.GetGuid(2); schema = reader.GetGuid(3); title = reader.GetString(4); description = reader.GetString(5); hash = reader.IsDBNull(6) ? null : reader.GetString(6); }
        var tags = new List<string>(); await using (var command = new SqlCommand($"SELECT tag FROM {Q("sk_document_tags")} WHERE document_id=@id ORDER BY tag", connection)) { command.Parameters.AddWithValue("@id", id); await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false); while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false)) tags.Add(reader.GetString(0)); }
        var values = new Dictionary<string, KnowledgeValue>(StringComparer.OrdinalIgnoreCase); await using (var command = new SqlCommand($"SELECT field_key,value_type,text_value,int_value,decimal_value,bool_value,datetime_value,guid_value FROM {Q("sk_document_values")} WHERE document_id=@id", connection)) { command.Parameters.AddWithValue("@id", id); await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false); while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false)) values[reader.GetString(0)] = ReadValue(reader); }
        return new KnowledgeDocumentRecord { Id = id, ExternalId = external, KnowledgeBaseId = kb, CollectionId = collection, SchemaId = schema, Title = title, Description = description, Tags = tags, Values = values, SourceHash = hash };
    }
    private static KnowledgeValue ReadValue(SqlDataReader reader) => (KnowledgeFieldType)reader.GetInt32(1) switch { KnowledgeFieldType.Text => KnowledgeValue.From(reader.IsDBNull(2) ? null : reader.GetString(2)), KnowledgeFieldType.Int64 => KnowledgeValue.From(reader.GetInt64(3)), KnowledgeFieldType.Decimal => KnowledgeValue.From(reader.GetDecimal(4)), KnowledgeFieldType.Boolean => KnowledgeValue.From(reader.GetBoolean(5)), KnowledgeFieldType.DateTimeOffset => KnowledgeValue.From(reader.GetFieldValue<DateTimeOffset>(6)), KnowledgeFieldType.Guid => KnowledgeValue.From(reader.GetGuid(7)), var type => throw new InvalidOperationException($"Unsupported stored value type {type}.") };

    private SqlServerCandidateQuery CandidateQuery(string table, string where) => new() { Table = $"{options.Schema}.{table}", ItemKeyColumn = "item_id", FieldNameColumn = "field_name", FingerprintColumn = "fingerprint", VectorColumn = "embedding", RecordJsonColumn = "record_json", FieldWeightColumn = "field_weight", AdditionalWhereSql = where, VectorDimensions = null, SearchMode = SqlServerVectorSearchMode.Exact };
    private async Task<Guid[]> ExpandCollectionsAsync(SqlConnection connection, IReadOnlyList<Guid> seeds, CancellationToken cancellationToken) { var names = new string[seeds.Count]; await using var command = new SqlCommand(); command.Connection = connection; for (var i = 0; i < seeds.Count; i++) { names[i] = $"@c{i}"; command.Parameters.AddWithValue(names[i], seeds[i]); } command.CommandText = $"WITH sk_scope AS (SELECT id FROM {Q("sk_collections")} WHERE id IN ({string.Join(',', names)}) UNION ALL SELECT c.id FROM {Q("sk_collections")} c JOIN sk_scope s ON c.parent_collection_id=s.id) SELECT DISTINCT id FROM sk_scope OPTION (MAXRECURSION 32767)"; var result = new List<Guid>(); await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false); while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false)) result.Add(reader.GetGuid(0)); return result.ToArray(); }
    private static string BuildScopeSql(IReadOnlyList<Guid> collections, out IReadOnlyList<SqlParameter> parameters) { var ps = new List<SqlParameter>(); parameters = ps; if (collections.Count == 0) return string.Empty; var names = new string[collections.Count]; for (var i = 0; i < collections.Count; i++) { names[i] = $"@sk_c{i}"; ps.Add(new SqlParameter(names[i], collections[i])); } return $" AND d.collection_id IN ({string.Join(',', names)})"; }
    private static SqlParameter Clone(SqlParameter p) => new(p.ParameterName, p.Value);

    private async Task<KnowledgeBaseRecord?> FindKnowledgeBaseAsync(SqlConnection connection, string title, string? externalId, CancellationToken cancellationToken) { await using var command = new SqlCommand(externalId is null ? $"SELECT TOP 1 id,external_id,title,description FROM {Q("sk_knowledge_bases")} WHERE title=@title" : $"SELECT TOP 1 id,external_id,title,description FROM {Q("sk_knowledge_bases")} WHERE external_id=@external", connection); command.Parameters.AddWithValue("@title", title.Trim()); command.Parameters.AddWithValue("@external", (object?)externalId ?? DBNull.Value); await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false); return await reader.ReadAsync(cancellationToken).ConfigureAwait(false) ? new KnowledgeBaseRecord { Id = reader.GetGuid(0), ExternalId = reader.IsDBNull(1) ? null : reader.GetString(1), Title = reader.GetString(2), Description = reader.GetString(3) } : null; }
    private async Task<KnowledgeCollectionRecord?> FindCollectionAsync(SqlConnection connection, Guid kb, string title, Guid? parent, string? externalId, CancellationToken cancellationToken) { await using var command = new SqlCommand(externalId is null ? $"SELECT TOP 1 id,default_schema_id,external_id,title,description FROM {Q("sk_collections")} WHERE knowledge_base_id=@kb AND title=@title AND ((@parent IS NULL AND parent_collection_id IS NULL) OR parent_collection_id=@parent)" : $"SELECT TOP 1 id,default_schema_id,external_id,title,description FROM {Q("sk_collections")} WHERE knowledge_base_id=@kb AND external_id=@external", connection); command.Parameters.AddWithValue("@kb", kb); command.Parameters.AddWithValue("@title", title.Trim()); command.Parameters.AddWithValue("@parent", (object?)parent ?? DBNull.Value); command.Parameters.AddWithValue("@external", (object?)externalId ?? DBNull.Value); await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false); return await reader.ReadAsync(cancellationToken).ConfigureAwait(false) ? new KnowledgeCollectionRecord { Id = reader.GetGuid(0), KnowledgeBaseId = kb, ParentCollectionId = parent, DefaultSchemaId = reader.IsDBNull(1) ? null : reader.GetGuid(1), ExternalId = reader.IsDBNull(2) ? null : reader.GetString(2), Title = reader.GetString(3), Description = reader.GetString(4) } : null; }
    private async Task<IReadOnlyList<string>> ReadCollectionTagsAsync(SqlConnection connection, Guid id, CancellationToken cancellationToken) { var result = new List<string>(); await using var command = new SqlCommand($"SELECT tag FROM {Q("sk_collection_tags")} WHERE collection_id=@id ORDER BY tag", connection); command.Parameters.AddWithValue("@id", id); await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false); while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false)) result.Add(reader.GetString(0)); return result; }

    private async Task<StoreMetadata?> ReadMetadataAsync(SqlConnection connection, CancellationToken cancellationToken) { await using var command = new SqlCommand($"SELECT database_version,active_vector_table,active_fingerprint,active_dimensions,pending_vector_table FROM {Q("sk_store_metadata")} WHERE singleton=1", connection); await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false); if (!await reader.ReadAsync(cancellationToken).ConfigureAwait(false)) return null; return new StoreMetadata(reader.GetInt32(0), reader.GetString(1), reader.GetString(2), reader.GetInt32(3), reader.IsDBNull(4) ? null : reader.GetString(4)); }
    private async Task InsertMetadataAsync(SqlConnection connection, KnowledgeStorageInitialization init, Guid generation, string table, CancellationToken cancellationToken) { await using var command = new SqlCommand($"INSERT INTO {Q("sk_store_metadata")}(singleton,store_id,engine_version,database_version,persistence_mode,active_generation,active_vector_table,active_fingerprint,active_dimensions) VALUES(1,@store,@engine,@db,@mode,@generation,@table,@fingerprint,@dimensions)", connection); command.Parameters.AddWithValue("@store", Guid.NewGuid()); command.Parameters.AddWithValue("@engine", EngineVersion); command.Parameters.AddWithValue("@db", init.DatabaseVersion); command.Parameters.AddWithValue("@mode", (int)init.PersistenceMode); command.Parameters.AddWithValue("@generation", generation); command.Parameters.AddWithValue("@table", table); command.Parameters.AddWithValue("@fingerprint", init.Embedding.EmbeddingSpaceFingerprint); command.Parameters.AddWithValue("@dimensions", init.Embedding.OutputDimensions); await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false); }
    private async Task SetPendingMetadataAsync(SqlConnection connection, KnowledgeStorageInitialization init, Guid generation, string table, CancellationToken cancellationToken) { await using var command = new SqlCommand($"UPDATE {Q("sk_store_metadata")} SET database_version=@db,persistence_mode=@mode,pending_generation=@generation,pending_vector_table=@table,pending_fingerprint=@fingerprint,pending_dimensions=@dimensions WHERE singleton=1", connection); command.Parameters.AddWithValue("@db", init.DatabaseVersion); command.Parameters.AddWithValue("@mode", (int)init.PersistenceMode); command.Parameters.AddWithValue("@generation", generation); command.Parameters.AddWithValue("@table", table); command.Parameters.AddWithValue("@fingerprint", init.Embedding.EmbeddingSpaceFingerprint); command.Parameters.AddWithValue("@dimensions", init.Embedding.OutputDimensions); await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false); }
    private async Task ClearPendingMetadataAsync(SqlConnection connection, CancellationToken cancellationToken) { await using var command = new SqlCommand($"UPDATE {Q("sk_store_metadata")} SET pending_generation=NULL,pending_vector_table=NULL,pending_fingerprint=NULL,pending_dimensions=NULL WHERE singleton=1", connection); await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false); }
    private async Task DropVectorTableIfExistsAsync(SqlConnection connection, string table, CancellationToken cancellationToken) { await using var command = new SqlCommand($"IF OBJECT_ID(N'{Q(table)}',N'U') IS NOT NULL DROP TABLE {Q(table)}", connection); await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false); }
    private string Q(string table) => $"{QI(options.Schema)}.{QI(table)}"; private static string QI(string id) => $"[{id.Replace("]", "]]", StringComparison.Ordinal)}]"; private static string VectorTableName(Guid generation) => "sk_vectors_" + generation.ToString("N");
    private static async Task ExecuteAsync(SqlConnection connection, SqlTransaction transaction, string sql, CancellationToken cancellationToken, params (string Name, object Value)[] parameters) { await using var command = new SqlCommand(sql, connection, transaction); foreach (var p in parameters) command.Parameters.AddWithValue(p.Name, p.Value); await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false); }
    private sealed record StoreMetadata(int DatabaseVersion, string ActiveVectorTable, string ActiveFingerprint, int ActiveDimensions, string? PendingVectorTable);
}
